### PR TITLE
Implement importing rig intrinsics from JSON (using tvec, qvec, rmat)

### PR DESCRIPTION
**Pull request by fishcu**

### CODE REVIEW

**Comment by fishcu** [comment]
@puzzlepaint is your code online?
I know it's bad to pull in dependencies in a PR like that, but I was in a hurry to get results back then and I figured it might be of use to some people at least. But I guess it's not visible enough to make a difference, since you re-implemented it anyway! ;)

**Comment by puzzlepaint** [comment]
I had the code as a part of some larger local changes. I now extracted it and pushed it here:
https://github.com/puzzlepaint/colmap/commit/e8701632d39317e245c0244512e09a2fa15e3f5f
In this form, this is untested. Also, I didn't tidy it up for a PR. For example, there is no warning about possible scale inconsistency if multiple rigs are given.

Once this PR gets merged the functionality should become more visible :)

**Comment by os-gabe** [comment]
I'm quite interested in this functionality. What are the chances of getting this merged?

**Comment by fishcu** [comment]
IIRC I used another json library for this. I think if someone got rid of that dependency, changes of a merge would be higher. 

You can still checkout this PR and compile it yourself if you want to have the functionality. But you will miss out on the latest commits unless you rebase.

**Comment by fishcu** [comment]
I will maybe try to submit a better pull request. This one was pretty terrible, but at least I have a reference now to quickly code a better one!

**Pull request closed without merging**
