### PR TITLE
Extend SceneClustering to support non-hierarchical (flat) clusters

### PR DESCRIPTION
**Pull request by anmatako**

### CODE REVIEW

**Comment by ahojnnes** [comment]
Would be great to add some unit tests to scene_clustering_test.cc to make sure this new functionality works as expected.

**Comment by anmatako** [comment]
> Would be great to add some unit tests to scene_clustering_test.cc to make sure this new functionality works as expected.

Unit tests added for flat clustering with and without overlaps.

**Comment by anmatako** [comment]
Tests will have to be revised. It appears that the graph cut is not fully deterministic in the order it assigns labels to clusters; the cluster sizes and the IDs in each cluster are as expected but the order may differ, e.g. cluster 0 on Windows may be cluster 1 in Ubuntu. Not sure why this is not being an issue with the unit tests for hierarchical clustering. New tests pass on Windows and Mac but fail in Ubuntu.

**Comment by anmatako** [comment]
Made the new flat clustering deterministic sorting by descending cluster size and using min image ID as tie breaker. Now the test should be consistent on all environments.

**Pull request merged**
