### PR TITLE
Add camera pointer in the image class

### PR DESCRIPTION
**Pull request by B1ueber2y**
This PR adds support for directly indexing cameras in the image class with backward compatibility. As one of the steps for enabling better rig design, an optional camera pointer is added into the image class, and get initialized with ``SyncCameraPointers`` in the reconstruction class. The IO is unchanged in this feature. 

As a byproduct, one can directly call image.ProjectPoint(point3d) when the camera pointer is initialized (will return None when the point is behind the camera). Relevant pybind is also supported.

```
import pycolmap
recon = pycolmap.Reconstruction("./pycolmap/example/sfm/0")
image = recon.images[1]
print(image.camera) 
# Camera(camera_id=1, model=SIMPLE_RADIAL, width=3072, height=2048, params=[2776.773904, 1536.000000, 1024.000000, -0.003993] (f, cx, cy, k))
print(image.project_point(np.array([0., 0., 0.]))) 
# [-1684.30411175  1236.07593196]
```

We could also think of many more interesting features to be added in the future (e.g. fundamental matrix from two image instances etc.) Also, as a debatable point, we could potentially require the pointer to be always initialized by deprecating the SetCameraId() interface.

### CODE REVIEW

**Comment by ahojnnes** [comment]
As an alternative, and I don't know if it's easily possible, we could require the camera to exist upon construction of an image. In other words, make it a required argument to the Image constructor.

**Comment by sarlinpe** [comment]
> As an alternative, and I don't know if it's easily possible, we could require the camera to exist upon construction of an image. In other words, make it a required argument to the Image constructor.

I agree that this would be nicer, but then the Camera object needs to be instantiated via a `shared_ptr` all throughout the codebase - is this reasonable? how about declaring `camera_` as `Camera*` instead of `shared_ptr<Camera>` to let the calling scope manage the lifetime of the object?

**Comment by ahojnnes** [comment]
> I agree that this would be nicer, but then the Camera object needs to be instantiated via a `shared_ptr` all throughout the codebase - is this reasonable? how about declaring `camera_` as `Camera*` instead of `shared_ptr<Camera>` to let the calling scope manage the lifetime of the object?

Agreed that the raw pointer can be better and thus not enforce a particular ownership model on the caller side.

**Comment by B1ueber2y** [comment]
I agree that this sounds nice. However, requiring a raw camera pointer at image construction will potentially make the design of the interfaces here much uglier then before: https://github.com/colmap/colmap/blob/main/src/colmap/scene/database.h#L156-L158.

**Comment by B1ueber2y** [comment]
> I agree that this sounds nice. However, requiring a raw camera pointer at image construction will potentially make the design of the interfaces here much uglier then before: https://github.com/colmap/colmap/blob/main/src/colmap/scene/database.h#L156-L158.

A random proposal to resolve this: we could do one level abstraction further by having class ``Image`` inheriting from something like ``ImageBase``, where the base abstraction is completely similar as the ``Image`` class in the COLMAP before, such that it does not hold the raw pointer of the camera and is only used in the ``Database`` readers.

**Comment by B1ueber2y** [comment]
Closed due to totally different design as it started. Reopening in a new PR.

**Pull request closed without merging**
