### PR TITLE
Sperical Central Camera Support

### PR DESCRIPTION
**Pull request by daleydeng**

### CODE REVIEW

**Comment by daleydeng** [comment]
Notice that, some unused function or related test are commented out, apply needed part~

**Comment by ahojnnes** [comment]
Hi @daleydeng ,

I will get to this soon. Have to finish some other stuff first though.

Best, Johannes

**Comment by daleydeng** [comment]
Allright, I found ray based representaion is also need cheirality check and the angular error check is enough.

If the calculated 3D point (by DLT method) is behind its observed ray directions (world point), the angular error is large (nearly M_PI), so check the angular error is enough for ray based representation.

new commit as:
https://github.com/daleydeng/colmap/commit/9c6c3092edb7eb4e6d70aa99bf3f999ddbd73c82

**Comment by spriglet66** [comment]
Would be amazing if spherical camera support could be implemented into the branch master as it would make my life so much easier! At the moment I have to process the spherical source images into cube map faces to then import into colmap which is a pain as it would be an unnessecary step!

Thank you so much!

**Comment by ahojnnes** [comment]
I don't have access to a spherical camera. If someone could capture a few datasets and share the data with me, I can try to implement this feature.

**Comment by spriglet66** [comment]
Hi Johannes, I have a spherical camera and a lot of datasets of buildings I hope to be able to reconstruct a mesh from that I can share with you. The implementation of support for a spherical camera would be of great use to me as I currently have to work round this problem by converting the equirectangular source images into 6 seperate cube faces which essentially and unnesecarily multiplies the number of images i have to enter into colmap by 6!

What is the easiest way to share my datasets with you?

Thanks!
Ross.

**Comment by ahojnnes** [comment]
I would just need the images along with additional parameters of the camera that you have. No need for the mesh.

**Comment by spriglet66** [comment]
Hi Johannes, Here is the link to download my dataset (unconverted to cube form). I have had good results from using the converted cubic images as input and could send a picture of the results so they can be compared against using the spherical images as input as soon as that feature is working?

https://1drv.ms/f/s!Ap7lni15eJp1h5EiqZEYYRo2ceTfpw

I will send another link to the cubic images as soon as I have organised them for you. 

Thanks,

Ross.

**Comment by ahojnnes** [comment]
@spriglet66 The file does not seem to exist anymore. Could you reshare it?

**Comment by spriglet66** [comment]
Hi sorry I've updated the link! Please let me know if you need anything else! I will send you a link to the converted cube images in the next hour! 

https://1drv.ms/f/s!Ap7lni15eJp1h5EiriArFPTMI1MhmA

Thanks,
Ross.

**Comment by WillWhiteneck** [comment]
I'm trying to make 3D point clouds from spherical images. Will this PR this get merged in?

**Comment by WillWhiteneck** [comment]
I'm trying to make 3D reconstructions from spherical images. Will this PR get merged in?

**Comment by ryanismert** [comment]
Hi @daleydeng and @ahojnnes any chance we can get this PR rebased to the head of dev? I'd love to kick the tires, and I'm happy to build my own, but my eyes start to swim trying to fix conflicts in camera_models.h, cost_functions.h, etc. :)

Better yet, actually merged?

Cheers! Ryan

**Comment by os-gabe** [comment]
I'm also very interested in spherical camera support. Wondering what the chances of merging this are?

**Comment by johannes-graeter** [comment]
thx for your great work everybody. Any chance this could get merged? How could I support?

**Pull request closed without merging**
