### PR TITLE
remove boost::regex dependency

### PR DESCRIPTION
**Pull request by BertaBescos**
I was able to compile by removing the boost/regex dependency (I just replaced every boost:: for std:: in the bitmap.cc file, similar to what is suggested in this issue (https://github.com/colmap/colmap/issues/36), and removing the regex dependency in the CMakeLists.txt. Actually, since this is the only place where boost/regex is used, and since it seems to be of an issue for other people, I will make a pull request with this change if that's ok.

### CODE REVIEW

**Comment by mgprt** [comment]
Note that std::regex support was experimental and basically broken for GCC < 4.9 (see https://stackoverflow.com/a/12665408), so this could lead to bugs on older systems (e.g. Ubuntu 14.04, which is still supported).

**Comment by tompollok** [comment]
Ubuntu 14.04 LTS is supported only until April 2019, which is very soon. There is already 16.04 and 18.04. I dont see why anybody should care to much about supporting old compilers in favour of using std library functionality.

**Comment by ahojnnes** [comment]
I am against breaking Ubuntu 14.04 for no reason and even if we break Ubuntu 14.04, then we should make sure there is a warning or something, because this is a silent bug that is not visible to the user. The regex just doesn’t work. In any case, there should be a way to make this work both under 14.04 and 18.10 - worst case with separate ifdef branches.

**Comment by Eberty** [comment]
It is possible make an ifdef to solve this issue?

**Comment by attilaolah** [comment]
> I am against breaking Ubuntu 14.04 for no reason […]

I think the reason was the compilation error. That said, 14.04 is no longer supported, I don't think it's worth the complexity introduced by adding an `#ifdef` guard.

At some point, this pull request should probably be merged, and people who have trouble compiling it on old systems can still reverse-apply the patch.

**Comment by ahojnnes** [comment]
Resolved with the latest commit in the dev branch. Thanks!

**Pull request closed without merging**
