### PR TITLE
enable high dpi scaling for qt > 5.6.0

### PR DESCRIPTION
**Pull request by tompollok**
This fix enables highdpi scaling of the qt widgets for high dpi monitors

### CODE REVIEW

**Comment by ahojnnes** [comment]
Thanks for the contribution. Can you please make this change against the dev branch? Otherwise I can also do it.

Since I don't have a High DPI monitor, can you show the difference between the before/after? Can you also make sure that you can still double click points/cameras for selection in the viewer? Thanks!

**Comment by tompollok** [comment]
It should be dev

grafik
Or what do you mean?

Ive got two 4K displays and with qt you have to add this extra line to make widgets appear properly. In my case all icons of your toolbar look very tiny and probabl also some labels arent rendered correctly.

This is before the patch:
grafik
Unfortunately i havent compiled the project yet on my machine. I hoped that i could download build artifacts but its not possible. Is it possible to download your precompiled 3rdparty dependency libraries somewhere? Im using the same msvc2015 64 compiler with qt 5.9

**Comment by ahojnnes** [comment]
Ah okay, I thought you made your changes in the master instead of the dev branch. My mistake, so all is fine. Thanks for fix. It should be very easy to compile COLMAP yourself under Windows, see https://colmap.github.io/install.html#build-script

**Comment by ahojnnes** [comment]
Thanks.

**Comment by tompollok** [comment]
Just a follow up, the difference between HighDPI enabled and disabled on a 4K display:

grafik

**Comment by ahojnnes** [comment]
Looks much better indeed. Thanks for the PR.

**Pull request merged**
