### PR TITLE
flann match

### PR DESCRIPTION
**Pull request by DaniilSNikulin**
As noted in [this](https://github.com/colmap/colmap/issues/165) issue, master version of COLMAP use brute force search for pairwise feature matching for both CPU and GPU.

This PR implement ANN search for CPU version of matching.
In my tests, ANN is 6-10 times faster than brute force.

Unfortunately, I could not save dot distance function.

I tried create dot distance function for FLANN:
```cpp
struct ReverseDotDistance {
  using ElementType = int;
  using ResultType = int;

  template <class Iterator1, class Iterator2>
  ResultType operator()(Iterator1 a, Iterator2 b, size_t size, ResultType /*worst_dist*/ = -1) const {
    ResultType result = ResultType();
    for (size_t i = 0; i < size; ++i) {
      result -= (*a++) * (*b++);
    }
    return result;
  }
};
```
However, dot distance [can't be use in kdtree forest search](https://github.com/mariusmuja/flann/issues/143#issuecomment-28808790)

Dot distance still can be use in KMeans search (like in [this](https://github.com/turian/flann-1.2) repo), but L2 distance faster and create same result. So i decided use L2 and addinional compute dot for found neighbors.
```cpp
for (Eigen::MatrixXi::Index d1_idx = 0; d1_idx < indices->rows(); ++d1_idx) {
  for (int n_idx = 0; n_idx < indices->cols(); ++n_idx) {
    const int d2_idx = indices->coeff(d1_idx, n_idx);
    distances->coeffRef(d1_idx, n_idx) = query_int.row(d1_idx).dot(dataset_int.row(d2_idx));
  }
}
```

### CODE REVIEW

**Comment by ahojnnes** [comment]
Do you have runtime comparisons for different number of features? There could be a potential further speedup when doing matching by computing the search tree only once and reusing it multiple times. In this context, it would be interesting to see the runtime of building the search tree vs. the actual search. Finally, we definitely need unit tests for this.

**Comment by ahojnnes** [comment]
Otherwise, this looks great, thanks for your contribution.

**Comment by DaniilSNikulin** [comment]
Performance testing showed: time of build index for flann is approximately 10% of query time. This correlation don't depend from number of features.

| number of features | brute force time | summary flann time | build flann time | query flann time |
|:-------------------------:|:---------------------:|:-----------------:|:--------------------:|:----------------------:|
| 100 | 0.0008 | 0.0082 | 0.0008 | 0.0073 |
|200 | 0.0033 | 0.0137 | 0.0016 | 0.0121 |
|400|0.0163|0.0269|0.0034|0.0235
800|0.0783|0.0552|0.0071|0.0480
1600|0.413|0.116|0.014|0.102
3200|5.65|0.24|0.03|0.21
6400|19.40|0.51|0.06|0.45
12800|55.6|1.2|0.1|1.1
25600|301.6|3.1|0.3|2.8

Build index only one times and memoize it could give a potential further speedup.
However, after I added momoization of flann index to `FeatureMatcherCache` via `LRUCache`, no improvements in real tasks were get.

Original flann matching:

```
==============================================================================
Custom feature matching
==============================================================================

Matching block [1/19] in 26.874s
Matching block [2/19] in 27.055s
Matching block [3/19] in 27.073s
Matching block [4/19] in 27.304s
Matching block [5/19] in 27.428s
Matching block [6/19] in 26.826s
Matching block [7/19] in 27.573s
Matching block [8/19] in 27.272s
Matching block [9/19] in 27.826s
Matching block [10/19] in 27.578s
Matching block [11/19] in 27.290s
Matching block [12/19] in 26.631s
Matching block [13/19] in 26.874s
Matching block [14/19] in 26.993s
Matching block [15/19] in 26.735s
Matching block [16/19] in 27.272s
Matching block [17/19] in 27.308s
Matching block [18/19] in 28.103s
Matching block [19/19] in 22.335s
Elapsed time: 8.539 [minutes]
```

Flann matching with memoization:

```
==============================================================================
Custom feature matching
==============================================================================

Matching block [1/19] in 27.616s
Matching block [2/19] in 26.995s
Matching block [3/19] in 27.186s
Matching block [4/19] in 27.508s
Matching block [5/19] in 27.273s
Matching block [6/19] in 27.455s
Matching block [7/19] in 27.234s
Matching block [8/19] in 27.138s
Matching block [9/19] in 27.721s
Matching block [10/19] in 27.569s
Matching block [11/19] in 26.939s
Matching block [12/19] in 26.871s
Matching block [13/19] in 26.907s
Matching block [14/19] in 27.057s
Matching block [15/19] in 26.899s
Matching block [16/19] in 26.750s
Matching block [17/19] in 27.036s
Matching block [18/19] in 28.284s
Matching block [19/19] in 21.933s
Elapsed time: 8.555 [minutes]
```

The reason for no improvements likely is my bad code,  but I have no idea what exactly slow done it.
The addition of memoization has led to major changes in the code. Cause of memoization did not give
improvements, it is not added in this PR.

Code with memoization could be found [here](https://github.com/DaniilSNikulin/colmap/tree/flann_with_memoization).

**Comment by ahojnnes** [comment]
This is great, I made a few small improvements and merged your PR into the dev branch. Thanks very much for the contribution and for the timings. Since the memoization only brings small runtime improvements, I will go with your suggested changes as is.

**Pull request merged**
