### PR TITLE
Update confusing text

### PR DESCRIPTION
**Pull request by oleg-alexandrov**
It is confusing to state that colmap needs a GPU, therefore it can export to the format of other packages.

### CODE REVIEW

**Comment by oleg-alexandrov** [comment]
I added another minor clarification.

**Comment by ahojnnes** [comment]
Thanks.

**Comment by ahojnnes** [comment]
I actually don't fully understand how the description of this PR relates to the actual changes in the text. Here, you talk about GPU but I don't see any text changes related to that?

**Comment by oleg-alexandrov** [comment]
Sorry. That is because of my second commit which I piled up upon the first. Here is the first commit:

https://github.com/colmap/colmap/pull/747/commits/6a7a145237f0658fd58ece994d5b99fd593d480b

Here I noted that the GPU functionality is not connected to the ability to export to other tools.

In the second commit:

https://github.com/colmap/colmap/pull/747/commits/575610284cfd85ea84f2dd327c6acf0a0ceb2dda

I added something about pinhole vs simple pinhole. 

I should have made two pull requests, normally, but they were small so I put them both together. 

Do let me know if something is still confusing.

**Comment by oleg-alexandrov** [comment]
I broke this into two more manageable pull requests that can be reviewed separately:

https://github.com/colmap/colmap/pull/777
https://github.com/colmap/colmap/pull/776

So closing this.

**Pull request closed without merging**
