### PR TITLE
Remove dead youtube link

### PR DESCRIPTION
**Pull request by wzel**

### CODE REVIEW

**Comment by attilaolah** [comment]
While you're here, you could also remove the three dead YouTube links from https://colmap.github.io/datasets.html. Only one of them seems to be working.

**Comment by ahojnnes** [comment]
I am working on a new tutorial video and also updated the dataset youtube links. Thanks.

**Comment by wzel** [comment]
May I close this and remove from my to-do list, then?

**Comment by ahojnnes** [comment]
This has been fixed in another PR, thanks.

**Pull request closed without merging**
