### PR TITLE
Update install instructions for Mac

### PR DESCRIPTION
**Pull request by Dawars**
Based on build pipeline
https://github.com/colmap/colmap/blob/main/.azure-pipelines/build-mac.yaml

Adresses https://github.com/colmap/colmap/issues/2253

### CODE REVIEW

**Comment by ahojnnes** [comment]
Thank you for the fix! Is the "export PATH" really necessary?

**Comment by Dawars** [comment]
The export is necessary when building within a conda env, otherwise we get
```
CMake Error at cmake/FindDependencies.cmake:149 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.4) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:85 (include)
```

Looks like `-DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5` isn't necessary when export is set but I'd leave both.

**Comment by fabiannagel** [comment]
Thanks for the update! I have to configure cmake using a different Qt5 directory `-DQt5_DIR=/opt/homebrew/Cellar/qt@5/5.15.11/lib/cmake/Qt5` but afterwards I can build successfully.

However, running `colmap` shows an issue with `ceres-solver` (2.2.0):
```
dyld[94243]: Library not loaded: /opt/homebrew/opt/ceres-solver/lib/libceres.3.dylib
  Referenced from: <E49DC923-FC2D-3F25-936E-CD93562B277F> /opt/homebrew/Cellar/colmap/3.8/bin/colmap
  Reason: tried: '/opt/homebrew/opt/ceres-solver/lib/libceres.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/ceres-solver/lib/libceres.3.dylib' (no such file), '/opt/homebrew/opt/ceres-solver/lib/libceres.3.dylib' (no such file), '/opt/homebrew/Cellar/ceres-solver/2.2.0_1/lib/libceres.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/ceres-solver/2.2.0_1/lib/libceres.3.dylib' (no such file), '/opt/homebrew/Cellar/ceres-solver/2.2.0_1/lib/libceres.3.dylib' (no such file)
```

I'm not sure why but I only have `libceres.4.dylib`, but manually providing a symlink fixed the issue for now.

**Comment by vidit98** [comment]
Hi @fabiannagel , can you please tell how did you manually specify symlink?

**Pull request merged**
