### PR TITLE
not refine camera intrinsics in local BA

### PR DESCRIPTION
**Pull request by is03wlei**

### CODE REVIEW

**Comment by ahojnnes** [comment]
Thanks for your pull request, but this will not work, unfortunately. We just don't want to refine the intrinsics if not all of the images of a camera are included in the local bundle. If all the images of a camera are included, the intrinsics should be optimized.

**Comment by is03wlei** [comment]
Should we extend refined_cameras to unordered_map and make use of it.
Besides, we need to decrease refined_cameras in DeRegisterImageEvent.
Although it would affect configurations of RefineAbsolutePose, it shouldn't be worse.

**Comment by ahojnnes** [comment]
This will take more effort, because bundle adjustment currently does not allow to specify constant intrinsics for individual images.

**Comment by is03wlei** [comment]
You mean we need to handle such case:
local bundle contains all images of camera 1 but some of images of camera 2.

**Comment by ahojnnes** [comment]
@is03wlei Yes, exactly.

**Comment by ahojnnes** [comment]
The issue is now fixed in the latest commit in the dev branch. Thanks.

**Pull request closed without merging**
