### PR TITLE
Remove check on Qt version

### PR DESCRIPTION
**Pull request by Skydes**
I'm on Ubuntu 18.04 and seeing the extra `-fPIC` flag added by Qt 5.9.5, as reported in https://github.com/colmap/colmap/issues/1753 https://github.com/colmap/colmap/issues/1813. Upgrading to cmake 3.26 does not help. I think that it's safer to remove the flag regardless of the Qt version.

### CODE REVIEW

**Comment by ahojnnes** [comment]
Are you stuck with 18.04? I was planning to not support 18.04 going forward, as its outdated default compiler/packages hold development back due to lack of C++14, etc.

**Comment by Skydes** [comment]
Nope I indeed need to update very soon...

**Comment by ahojnnes** [comment]
I would rather add the 5.9.5 version explicitly, as it does appear to be fixed for the Qt version under 20.04 and 22.04. It sounds a little dangerous to mess with the default flags across all versions.

**Comment by ahojnnes** [comment]
Looked at the cmake bug again and also the special casing here. I think we can go ahead as proposed by you. Thanks.

**Pull request merged**
